CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTS` (
  `CLIENT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DEL CLIENTE',
  `USERNAME` VARCHAR(50) NOT NULL COMMENT 'NOMBRE DE USUARIO DEL CLIENTE',
  `DOCUMENT_TYPE` INT NOT NULL COMMENT 'TIPO DEL DOCUMENTO',
  `DOCUMENT_NUMBER` VARCHAR(20) NOT NULL COMMENT 'NUMERO DE DOCUMENTO DEL CLIENTE',
  `FULLNAME` VARCHAR(255) NOT NULL COMMENT 'NOMBRE COMPLETO',
  `POSTAL_CODE` VARCHAR(10) NOT NULL COMMENT 'CODGIO POSTAL',
  `ADDRESS` VARCHAR(255) NOT NULL COMMENT 'DIRECCION',
  `EMAIL` VARCHAR(255) NOT NULL COMMENT 'EMAIL DEL CLIENTE',
  `PASSWORD` VARCHAR(50) NOT NULL COMMENT 'CONTRASEÑA DEL CLIENTE',
  PRIMARY KEY (`CLIENT_ID`),
  UNIQUE INDEX `CLIENT_ID_UNIQUE` (`CLIENT_ID` ASC),
  UNIQUE INDEX `DOCUMENT_NUMBER_UNIQUE` (`DOCUMENT_NUMBER` ASC),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENT_CARD_INFORMATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENT_CARD_INFORMATION` (
  `CARD_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DE LA TARJETA',
  `CARD_NUMBER` VARCHAR(16) NOT NULL COMMENT 'NUMERO DE LA TARJETA',
  `CARD_EXPIRATION` DATE NOT NULL COMMENT 'VENCIMIENTO DE LA TARJETA',
  `CARD_NAME` VARCHAR(255) NOT NULL COMMENT 'NOMBRE DEL TITULAR DE LA TARJETA',
  `CLIENT_ID` INT NOT NULL,
  PRIMARY KEY (`CARD_ID`),
  UNIQUE INDEX `CARD_ID_UNIQUE` (`CARD_ID` ASC),
  UNIQUE INDEX `CLIENT_ID_UNIQUE` (`CLIENT_ID` ASC),
  CONSTRAINT `CLIENT_ID`
    FOREIGN KEY (`CLIENT_ID`)
    REFERENCES `mydb`.`CLIENTS` (`CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SHOPPING CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SHOPPING CART` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENTS_CLIENT_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `CLIENTS_CLIENT_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_SHOPPING CART_CLIENTS2_idx` (`CLIENTS_CLIENT_ID` ASC),
  CONSTRAINT `fk_SHOPPING CART_CLIENTS2`
    FOREIGN KEY (`CLIENTS_CLIENT_ID`)
    REFERENCES `mydb`.`CLIENTS` (`CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SELLER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SELLER` (
  `SELLER_ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) NOT NULL,
  `DOCUMENT_TYPE` INT NOT NULL,
  `DOCUMENT_NUMBER` VARCHAR(20) NOT NULL,
  `FULLNAME` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255) NOT NULL,
  `POSTAL_CODE` VARCHAR(10) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SELLER_ID`),
  UNIQUE INDEX `SELLER_ID_UNIQUE` (`SELLER_ID` ASC),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `DOCUMENT_NUMBER_UNIQUE` (`DOCUMENT_NUMBER` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POSTS` (
  `POST_ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL COMMENT 'TITULO DE LA PUBLICACION',
  `DESCRIPTION` VARCHAR(3000) NOT NULL COMMENT 'DESCRIPCION DE LA PUBLICACION',
  `PRICE` INT(20) NOT NULL,
  `SCORE` FLOAT(1) NOT NULL,
  `FEATURES` VARCHAR(1000) NOT NULL,
  `SELLER_ID` INT NOT NULL,
  PRIMARY KEY (`POST_ID`),
  UNIQUE INDEX `POST_ID_UNIQUE` (`POST_ID` ASC),
  INDEX `fk_POSTS_SELLER1_idx` (`SELLER_ID` ASC),
  CONSTRAINT `fk_POSTS_SELLER1`
    FOREIGN KEY (`SELLER_ID`)
    REFERENCES `mydb`.`SELLER` (`SELLER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SHOPPING CART_has_POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SHOPPING CART_has_POST` (
  `SHOPPING CART_ID` INT NOT NULL,
  `SHOPPING CART_CLIENT_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  PRIMARY KEY (`SHOPPING CART_ID`, `SHOPPING CART_CLIENT_ID`, `POST_ID`),
  INDEX `fk_SHOPPING CART_has_POST_POST1_idx` (`POST_ID` ASC),
  INDEX `fk_SHOPPING CART_has_POST_SHOPPING CART1_idx` (`SHOPPING CART_ID` ASC, `SHOPPING CART_CLIENT_ID` ASC),
  CONSTRAINT `fk_SHOPPING CART_has_POST_SHOPPING CART1`
    FOREIGN KEY (`SHOPPING CART_ID` , `SHOPPING CART_CLIENT_ID`)
    REFERENCES `mydb`.`SHOPPING CART` (`ID` , `CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHOPPING CART_has_POST_POST1`
    FOREIGN KEY (`POST_ID`)
    REFERENCES `mydb`.`POSTS` (`POST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SHOPPING CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SHOPPING CART` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENTS_CLIENT_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `CLIENTS_CLIENT_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_SHOPPING CART_CLIENTS2_idx` (`CLIENTS_CLIENT_ID` ASC),
  CONSTRAINT `fk_SHOPPING CART_CLIENTS2`
    FOREIGN KEY (`CLIENTS_CLIENT_ID`)
    REFERENCES `mydb`.`CLIENTS` (`CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POST_has_SHOPPING CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POST_has_SHOPPING CART` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `POST_ID` INT NOT NULL,
  `SHOPPING CART_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `POST_ID`, `SHOPPING CART_ID`),
  INDEX `fk_POST_has_SHOPPING CART_SHOPPING CART1_idx` (`SHOPPING CART_ID` ASC),
  INDEX `fk_POST_has_SHOPPING CART_POST1_idx` (`POST_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_POST_has_SHOPPING CART_POST1`
    FOREIGN KEY (`POST_ID`)
    REFERENCES `mydb`.`POSTS` (`POST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POST_has_SHOPPING CART_SHOPPING CART1`
    FOREIGN KEY (`SHOPPING CART_ID`)
    REFERENCES `mydb`.`SHOPPING CART` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMMENT` (
  `COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `TEXT` VARCHAR(3000) NOT NULL COMMENT 'COMENTARIO',
  `SCORE` FLOAT(1) NOT NULL COMMENT 'PUNTAJE DEL PRODUCTO',
  `DATE` DATE NOT NULL,
  `CLIENT_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  PRIMARY KEY (`COMMENT_ID`, `CLIENT_ID`, `POST_ID`),
  UNIQUE INDEX `COMMENT_ID_UNIQUE` (`COMMENT_ID` ASC),
  INDEX `fk_COMMENT_CLIENTS1_idx` (`CLIENT_ID` ASC),
  INDEX `fk_COMMENT_POSTS1_idx` (`POST_ID` ASC),
  CONSTRAINT `fk_COMMENT_CLIENTS1`
    FOREIGN KEY (`CLIENT_ID`)
    REFERENCES `mydb`.`CLIENTS` (`CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENT_POSTS1`
    FOREIGN KEY (`POST_ID`)
    REFERENCES `mydb`.`POSTS` (`POST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SELLER_CARD_INFORMATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SELLER_CARD_INFORMATION` (
  `CARD_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DE LA TARJETA',
  `CARD_NUMBER` VARCHAR(16) NOT NULL COMMENT 'NUMERO DE LA TARJETA',
  `CARD_EXPIRATION` DATE NOT NULL COMMENT 'VENCIMIENTO DE LA TARJETA',
  `CARD_NAME` VARCHAR(255) NOT NULL COMMENT 'NOMBRE DEL TITULAR DE LA TARJETA',
  `SELLER_ID` INT NOT NULL,
  PRIMARY KEY (`CARD_ID`, `SELLER_ID`),
  UNIQUE INDEX `CARD_ID_UNIQUE` (`CARD_ID` ASC),
  INDEX `fk_CLIENT_CARD_INFORMATION_copy1_SELLER1_idx` (`SELLER_ID` ASC),
  CONSTRAINT `fk_CLIENT_CARD_INFORMATION_copy1_SELLER1`
    FOREIGN KEY (`SELLER_ID`)
    REFERENCES `mydb`.`SELLER` (`SELLER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SAVED_POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SAVED_POSTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENTS_CLIENT_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_SAVED_POSTS_CLIENTS1_idx` (`CLIENTS_CLIENT_ID` ASC),
  CONSTRAINT `fk_SAVED_POSTS_CLIENTS1`
    FOREIGN KEY (`CLIENTS_CLIENT_ID`)
    REFERENCES `mydb`.`CLIENTS` (`CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SAVED_POSTS_has_POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SAVED_POSTS_has_POSTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SAVED_POSTS_ID` INT NOT NULL,
  `POSTS_POST_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `SAVED_POSTS_ID`, `POSTS_POST_ID`),
  INDEX `fk_SAVED_POSTS_has_POSTS_POSTS1_idx` (`POSTS_POST_ID` ASC),
  INDEX `fk_SAVED_POSTS_has_POSTS_SAVED_POSTS1_idx` (`SAVED_POSTS_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_SAVED_POSTS_has_POSTS_SAVED_POSTS1`
    FOREIGN KEY (`SAVED_POSTS_ID`)
    REFERENCES `mydb`.`SAVED_POSTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SAVED_POSTS_has_POSTS_POSTS1`
    FOREIGN KEY (`POSTS_POST_ID`)
    REFERENCES `mydb`.`POSTS` (`POST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
